# Generated by Django 3.2.6 on 2021-08-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=700, verbose_name='Description')),
                ('price', models.FloatField(verbose_name='Price')),
                ('rating', models.FloatField(verbose_name='Rating (out of 5)')),
                ('reviewCount', models.CharField(max_length=10, verbose_name='ReviewCount')),
                ('url', models.URLField(verbose_name='url')),
            ],
        ),
    ]
