# Generated by Django 3.2.6 on 2021-08-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_items', '0002_alter_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
